use University2

Select [Name], (Hiredate - (Salary/Commission)) from TEACHER

SELECT DEPARTMENT.Name , ROOM.Num , TEACHER.Name , LECTURE.Type , LECTURE.Week , LECTURE.Day
FROM DEPARTMENT ,ROOM,TEACHER,LECTURE
WHERE LECTURE.Day = 'пон' AND LECTURE.Week = 1 AND LECTURE.Type = 'лекция' and 
DEPARTMENT.Building = ROOM.Building and 
TEACHER.DepFK = DEPARTMENT.DepPK and 
TEACHER.DepFK = DEPARTMENT.DepPK and 
LECTURE.TchFK = TEACHER.TchPK and
LECTURE.RomFK = ROOM.RomPK


SELECT FACULTY.Name , DEPARTMENT.Name , TEACHER.Name
FROM DEPARTMENT, FACULTY , TEACHER
WHERE DEPARTMENT.DepPK = FACULTY.DepFK AND TEACHER.DepFK = DEPARTMENT.DepPK AND
DEPARTMENT.Name = 'Кафедра інженерії програмного забезпечення'

Select TEACHER.Name , TEACHER.Name , TEACHER.Hiredate,TEACHER.ChiefFK from DEPARTMENT , TEACHER 
Where TEACHER.ChiefFK IS NOT NULL AND DEPARTMENT.DepPK = TEACHER.DepFK
AND TEACHER.Hiredate BETWEEN '01.10.2001' AND '31.12.2001' 

Select FACULTY.Name , TEACHER.Salary , TEACHER.Hiredate,TEACHER.Name from FACULTY , DEPARTMENT , TEACHER
Where  DEPARTMENT.DepPK = FACULTY.DepFK AND TEACHER.DepFK = DEPARTMENT.DepPK AND 
UPPER(TEACHER.Hiredate) IN (' 01.02.2000' , '2001-02-01', '01.04.2000' , '01.05.2000' ) OR TEACHER.Salary BETWEEN 500 AND 800

SELECT F1.Name AS FAC1, F2.Name AS FAC2 , F1.Fund , F2.Fund FROM FACULTY AS F1 , FACULTY AS F2
WHERE  F1.Fund > F2.Fund + 1000

Select grp.Num , grp.Rating from SGROUP as grp , FACULTY , DEPARTMENT
Where DEPARTMENT.DepPK = grp.DepFK AND FACULTY.FacPK = DEPARTMENT.DepPK 
and
(NOT (grp.Course != 5 AND FACULTY.[Name] != 'компьютерные системы')
OR ((FACULTY.Fund between  15000 AND 300000) AND grp.Rating >= 40)
OR(FACULTY.Fund >= 200000 AND (grp.Rating between 20 and 50)))

